rungwiroon/BlazorGoogleMaps

BlazorGoogleMaps.sln
GoogleMapsComponents/MapComponent.cs
GoogleMapsComponents/Maps/LatLngBounds.cs
README.md
ServerSideDemo/Pages/MapMarker.razor
ServerSideDemo/appsettings.Development.json

Based on the documented API surface that can be found [here](https://developers.google.com/maps/documentation/javascript/reference/coordinates#LatLngBounds)
Update the server-side demo app's MapMarker page so it now tracks markers to a bounds object and added a button that sets the map zoom/position to encompass the added markers.

Added support for LatLngBounds object

---

GoogleMapsComponents/Maps/Rectangle.cs

Hi Rungwiroon!
To allow Rectangle to handle callbacks like Marker can, I copied the 2 AddListener() methods from Marker to Rectangle.  If this change is acceptable to you, and it's not too much trouble, can you also create a new nuget package including this change?
I am using GoogleMapsComponents in my project and it is working beautifully.
Thank you so much for making and maintaining this library!
Tzu-Han

Add AddListener() methods to Rectangle class.

---

GoogleMapsComponents/Maps/DirectionsLeg.cs
GoogleMapsComponents/Maps/Places/PlacePlusCode.cs
GoogleMapsComponents/Maps/Places/PlaceResult.cs
GoogleMapsComponents/Maps/TrafficModel.cs
GoogleMapsComponents/wwwroot/objectManager.js

We were having trouble requesting direction requests with a departure time set in the driving options (in order to get back a duration in traffic rather than just duration).
This code converts all ISO 8601 formatted strings into date objects which fixed the problem. It should also work with the transit options as well but we haven't tested it.

Return DurationInTraffic when setting a DepartureTime in DrivingOptions by converting all ISO 8601 formatted strings into date objects

---

GoogleMapsComponents/Maps/DirectionsRoute.cs
GoogleMapsComponents/wwwroot/objectManager.js

Hi there,
This code enables the return of the OverviewPolyline property in a DirectionsRoute of a DirectionsResult.
Not sure why it was purposefully being removed from the object returned from js.
Without this modification, the AddDirections method in MapRoutes demo page would not return any value to the OverviewPolyline property of the routes in the _directionsResult.

Return OverviewPolyline in DirectionsRoute object

---

GoogleMapsComponents/Maps/DirectionsRenderer.cs
GoogleMapsComponents/wwwroot/objectManager.js

Thanks @valentasm1 for the changes made in pull request #48.
Further to that, here I have added an optional `DirectionsRequestOptions` to `DirectionsRenderer.GetDirections`.
This is useful if you want to add a listener for `directions_changed` to your `DirectionsRenderer` to get the latest `DirectionsResult` after user interaction with the map.
I'm really not sure about the javascript changes I made so please take a close look at that. I'm not very familiar with js.
The following code changes for MapRoutes.razor.cs allow a user to alter the displayed route on the map and still generate distance and duration totals.
```
private async Task OnAfterInitAsync()
{
//Create instance of DirectionRenderer
dirRend = await DirectionsRenderer.CreateAsync(map1.JsRuntime, new …
```

Add optional DirectionsRequestOptions to DirectionsRenderer.GetDirections

---

GoogleMapsComponents/GoogleMapsComponents.csproj
GoogleMapsComponents/Helper.cs
GoogleMapsComponents/JsObjectRef.cs
GoogleMapsComponents/Maps/Extension/MarkerList.cs
GoogleMapsComponents/Maps/Marker.cs
GoogleMapsComponents/wwwroot/objectManager.js

Created MarkerList class extension -> 
- Dictionary<string, Marker> of Marker
- Almost all Get & Set method for marker extended to MarkerList (but not EventHandlers management -> it can very dangerous set a huge number of Listener at the same time...)
Added some features to Marker class ->
-  Added a public readonly ```Dictionary<string, List<MapEventListener>> EventListeners``` to keep trace of eventually defined EventListener (key of Dictionary it's obviously the EventName)
- Added ClearListeners to clean all eventually defined Marker's Listener for that eventName
---
It's almost all tested ->
MarkerList as class and functionalities, in details I've used massively SetPositions / GetPositions, GetVisibles / SetVisibles methods, so as for Marker Class the new method ClearListeners
--- …

Added MarkerList class as extension, added some feature to Marker class

---

GoogleMapsComponents/Maps/Extension/MarkerList.cs
GoogleMapsComponents/Maps/InfoWindow.cs

Added (as previous defined, please check if I lost something) MarkerList class summary
Updated InfoWindow class to be coherent with updated Marker class paradigm, so:
a) imposed descendance from IJsObjectRef
b) implemented IJsObjectRef exposing public Guid Guid => _jsObjectRef.Guid
c) added listener management methods:
c1) AddListener
c2) AddListener<T>
c3) ClearListeners
d) due to "c" points, a new member is been exposed as a:
public readonly Dictionary<string, List<MapEventListener>> EventListeners
so, dev user can keep under control if "object" (InfoWindow in this context) has yet a "eventName" associated with a specific eventListerner or not before adding a new one, and - at the same time - dev user has a simply way to remove all eventually associated eventListerner(s) to a …

InfoWindow class extension (coherently with Marker class) an other little refinements

---

ServerSideDemo/Pages/_Host.cshtml

According to https://github.com/googlemaps/js-markerclustererplus, this is the new reference to use.

Updated marker clusterer reference in demo app.

---

README.md

Fixes https://github.com/rungwiroon/BlazorGoogleMaps/issues/91.

Added hint to use JS script reference for marker clustering.

---

GoogleMapsComponents/Maps/DirectionsService.cs
GoogleMapsComponents/wwwroot/objectManager.js

Hi there,
We are wanting to have `DirectionsService.Route` return a `DirectionsResult`. We have been (and still do) use `DirectionsRenderer.Route` to do this, but we wanted to be able to query the Api without displaying the results on the map.
We investigated making HTTP calls directly to the Directions Api but Google blocks this (through CORS) when you are calling from a browser (as in Blazor WebAssembly) so the only option is the use the Javascript Api.
The original `DirectionsService.Route` returned a `DirectionResponse` but on inspecting the code it was always null.
To solve the issue we copied the code from the `DirectionsRenderer.Route` method. We also had to change `objectManager.js` to ensure that the `setDirections` method was only called if it existed. `setDirections` does exist …

Make DirectionsService.Route method return a DirectionsResult

---

README.md

The necessary javascript that is required for clustering is slightly different between server and client side blazor projects.  Modified the readme to clarify the subtle difference. 
Closes #123

Clarified how to include scripts for clustering

---

GoogleMapsComponents/Maps/MapTypeStyle.cs

For my project, I needed to be able to use an additional GoogleMaps Style - Lightness.  I noticed that BlazorGoogleMaps didn't yet implement it, so added it along with Saturation and Weight.  I hope this may be useful to you.

Added new stylers for Lightness, Saturation, and Weight.

---

GoogleMapsComponents/Maps/MarkerClustererOptions.cs
GoogleMapsComponents/Maps/MarkerClustering.cs

This PR is just to expose the `Repaint` method for the marker clusterer.  The use case is for where map markers are added, removed, changed visibility, or changed position - calling `Repaint()` after any such changes ensures that the clustered markers reflect the updated situation.

Added Repaint method to MarkerClustering.  Updated some xml comments.

---

ClientSideDemo/wwwroot/index.html
ClientSideDemoNet5/wwwroot/index.html
GoogleMapsComponents/GoogleMap.razor
GoogleMapsComponents/GoogleMapsComponents.csproj
GoogleMapsComponents/Maps/ImageMapType.cs
GoogleMapsComponents/Maps/Map.cs
GoogleMapsComponents/wwwroot/js/objectManager.js
ServerSideDemo/Pages/MapImageOverlay.razor
ServerSideDemo/Pages/_Host.cshtml
ServerSideDemo/ServerSideDemo.csproj
ServerSideDemo/Shared/NavMenu.razor

I'm not 100% on if this implementation is imageMapType is good (kinda specific url format), but its a start.  The important part is adding the eval() fallback in the tryParseJson.  This allows us to include functions in the json string we use to initialize the imageMapType.  I also bumped things to .net 5 (even though .net 6 is is out, now) so we could employ js isloation.  I started trying to implement loading of google maps js in the component library, but I ran into CORS issues (what else is new).
+employed js isolation so users don't not have to reference the .js file, themselves.
+Added ImageMapType and supporting js for show/hide layers
Server-side demo changed to .net 5 (for js isolation)
_Host.cshtml removed reference to objectManager.js
"Events" page of server side demo works …

moved objectManager to /js folder; implemented ImageMapType

---

ServerSideDemo/wwwroot/css/site.css

Desktop sidebar will now scroll instead of extending the page when there are too many items for the screen height. This fixes items rendered below the page being unreadable due to white text on white background with smaller view heights.

make desktop mode sidebar scroll overflow-y

---

GoogleMapsComponents/Maps/Extension/MarkerList.cs
ServerSideDemo/Pages/MapMarker.razor.cs

`MarkerList.SetLabels()` was using the wrong value type. Added overloads to match the reference docs: (https://developers.google.com/maps/documentation/javascript/reference/3.47/marker#Marker.setLabel)
Added missing OneOf overloads for `MarkerList.SetIcons()` 
Found an undocumented event in the MarkerClusterer module which is a better logical trigger for the deferred Marker AddListener I added to the server demo. (Open MarkerClusterer issue for adding missing docs: https://github.com/googlemaps/js-markerclusterer/issues/161)

MarkerList API improvements & use better event in server example

---

GoogleMapsComponents/Maps/MapEventListener.cs
GoogleMapsComponents/Maps/MarkerClustering.cs
ServerSideDemo/Pages/MapMarker.razor.cs

In pull request https://github.com/rungwiroon/BlazorGoogleMaps/pull/182, I misunderstood part of the issue with the MapEventListener not removing properly. The console error about a 'remove' function not existing was because the listener object had already been disposed from BlazorGoogleMap's reference dict (or hadn't been added to it), not because there isn't a remove() on the MapEventListener class.
The real source of the problem was that the latest js-markerclusterer doesn't have a clearListeners() function like the old version. Listeners need to be cleared individually/separately. 
This pull request reverts MapEventListener to correctly call remove() as before, and fixes MarkerClusterer.clearListeners() to loop through listeners it's trying to remove.

fix markerclusterer clearListeners to work with new js-markerclusterer

---

GoogleMapsComponents/Maps/MarkerClustering.cs
GoogleMapsComponents/wwwroot/js/objectManager.js

Adds missing access to js module functions methods `addMarkers` and `removeMarkers`. Singular item add/remove methods exist but I didn't bother since users can pass an enumerable of length one.
Also added support for the optional `noDraw` parameter to `ClearMarkers()`, and removed the call to `render()` since the underlying `clearMarkers()` function does that automatically when `noDraw` is false (default).

Implement AddMarkers() and RemoveMarkers in iMarkerClustering

---

ClientSideDemoNet5/Pages/MapMarker.razor
GoogleMapsComponents/Maps/DirectionsRenderer.cs
GoogleMapsComponents/Maps/ListableEntityBase.cs
GoogleMapsComponents/wwwroot/js/objectManager.js
ServerSideDemo/Pages/MapPolyline.razor

ZoomOnClick option was not functional because C# forces json property first char to lower case.
fixes Nullability errors that were preventing compile on Rebuild All
Fixes crash in ServerSideDemo where code attempted to access `polyline` while it is null.

ZoomOnClick for MarkerClusterer, nullability, and MapPolyline demo

---

GoogleMapsComponents/Maps/MarkerClustererOptions.cs
GoogleMapsComponents/wwwroot/js/objectManager.js
ServerSideDemo/Pages/MapMarker.razor.cs

This makes it possible to set a custom `render` or `algorithm` function via MarkerClustererOptions without needing to host a custom version of `objectManager.js` to set the option when instantiating the `js-markerclusterer` object. 
Example of usage is added to `objectManager.js` and `MapMarker.razor.cs` in ServerSideDemo, but commented out as most people will probably want the defaults.

Render and algorithm settings for MarkerClustererOptions 

---

GoogleMapsComponents/GoogleMapsComponents.csproj

Bumping OneOf to 3.0 since they have changed reference from NetStandard.Library which contains some vurnable parts. Went through all examples and it did not break anything nor did I have to change anything in the code. 
Unless someone else has a reason this should not be done I think this is something simple and always good to keep the dependencies up to date.

Bum OneOf from 2.1 to 3.0

---

GoogleMapsComponents/wwwroot/js/objectManager.js
ServerSideDemo/Pages/MapPolyline.razor

Currently, `Polygon.GetPaths` produces an exception in JS. This PR will process the nested MVCArray from the Maps API before returning.
Additionally, a demo for Polygon.GetPaths is added based on Google's [Polygon With Hole](https://developers.google.com/maps/documentation/javascript/examples/polygon-hole) .
**The exception**
```
Error: Microsoft.JSInterop.JSException: An exception occurred executing JS interop: The JSON value could not be converted to System.Collections.Generic.IEnumerable`1[GoogleMapsComponents.Maps.LatLngLiteral]. Path: $[0] | LineNumber: 0 | BytePositionInLine: 2.. See InnerException for more details.
---> System.Text.Json.JsonException: The JSON value could not be converted to System.Collections.Generic.IEnumerable`1[GoogleMapsComponents.Maps.LatLngLiteral]. Path: …
```

Fix Polygon.GetPaths JS exception

---

GoogleMapsComponents/wwwroot/js/objectManager.js

Saw that this reduced my large MarkerList object creation time by about 10%, so went ahead and applied the principle to all the other JS loops that didn't already have it.

optimize JS loops to only read array lengths once

---

GoogleMapsComponents/Maps/Data/StyleOptions.cs
ServerSideDemo/Pages/MapDataPage.razor

Fixed naming of Data.StyleOptions.FillColor (was previously `Fillcolor`, which was ignored by GoogleMaps javascript API because of case-sensitivity).  Added a demonstration in the MapData page to load (and fill-in!) a GeoJson polygon.

Fixed Data.StyleOptions.FillColor naming

---

GoogleMapsComponents/Maps/CircleOptions.cs
GoogleMapsComponents/Maps/MapTypeId.cs
GoogleMapsComponents/Maps/PolygonOptions.cs
GoogleMapsComponents/Maps/RectangleOptions.cs
GoogleMapsComponents/Maps/StrokePosition.cs
GoogleMapsComponents/Maps/SymbolPath.cs

Serializing these enums as strings (e.g. "CIRCLE" and "Center") either breaks the constructor in objectManager.createObject() or causes a `TypeError: h[r] is not a function` error during drawing.
Can be checked with the polyline and drawing manager demo pages.

enum serialization for StrokePosition and SymbolPath

---

GoogleMapsComponents/GoogleMap.razor
GoogleMapsComponents/Maps/Data.cs
GoogleMapsComponents/Maps/DirectionsRenderer.cs
GoogleMapsComponents/Maps/Drawing/DrawingManager.cs
GoogleMapsComponents/Maps/Event.cs
GoogleMapsComponents/Maps/Extension/EventEntityBase.cs
GoogleMapsComponents/Maps/GroundOverlay.cs
GoogleMapsComponents/Maps/ImageMapType.cs
GoogleMapsComponents/Maps/InfoWindow.cs
GoogleMapsComponents/Maps/ListableEntityBase.cs
GoogleMapsComponents/Maps/Map.cs
GoogleMapsComponents/Maps/MapEventListener.cs
GoogleMapsComponents/Maps/MarkerClustering.cs
GoogleMapsComponents/Maps/Places/Autocomplete.cs
GoogleMapsComponents/Maps/Rectangle.cs
GoogleMapsComponents/wwwroot/js/objectManager.js
ServerSideDemo/Pages/MapEvents.razor

This adds the ability to only have a event listen once and then never trigger again. Useful for when you want to do something like fixing zoom after idle but not triggering on every idle. 
Not sure about which is the best standard to use for eventListeners since it's somewhat different across the project. As you can see in this [https://github.com/rungwiroon/BlazorGoogleMaps/blob/89e8239ac05cf9c230eaf12e958995542163741f/GoogleMapsComponents/Maps/ListableEntityBase.cs#L61](file) we prevent duplicates, but not in all the places. Added a note in my new base class for the possibility of this. Could be configured per entity type aswell but for now I left those untouched.

Added support for AddListenerOnce

---

GoogleMapsComponents/Maps/PolylineOptions.cs

This PS allows one to hide the undo button in the drawing manager by adding the undocumented suppressUndo parameter to the PolygonOptions class.

Add drawingManager suppressUndo undocumented parameter.

---

GoogleMapsComponents/ExceptionExtensions.cs
GoogleMapsComponents/MapComponent.cs

e.g. upon page refresh  
Note: Unfortenatly, JSDisconnectedException is available in dotnet >= 6.0, and not in dotnet standard, so esentially all exceptions are swalloed in `MapComponent::DisposeAsyncCore`
Fixes #272

Handling JSDisconnectedExceptions when disposing map after circuit was disconnected

---

GoogleMapsComponents/Helper.cs
GoogleMapsComponents/Maps/AdvancedMarkerViewOptions.cs
GoogleMapsComponents/Maps/Animation.cs
GoogleMapsComponents/Maps/CircleOptions.cs
GoogleMapsComponents/Maps/CollisionBehavior.cs
GoogleMapsComponents/Maps/ControlPosition.cs
GoogleMapsComponents/Maps/DirectionsRequest.cs
GoogleMapsComponents/Maps/DirectionsStatus.cs
GoogleMapsComponents/Maps/Drawing/OverlayType.cs
GoogleMapsComponents/Maps/GeocoderGeometry.cs
GoogleMapsComponents/Maps/GeocoderLocationType.cs
GoogleMapsComponents/Maps/GeocoderResponse.cs
GoogleMapsComponents/Maps/GeocoderStatus.cs
GoogleMapsComponents/Maps/MapOptions.cs
GoogleMapsComponents/Maps/MapTypeId.cs
GoogleMapsComponents/Maps/MarkerOptions.cs
GoogleMapsComponents/Maps/Places/AutocompleteResponse.cs
GoogleMapsComponents/Maps/Places/PlaceResponse.cs
GoogleMapsComponents/Maps/Places/PlaceServiceStatus.cs
GoogleMapsComponents/Maps/Places/QueryAutocompleteResponse.cs
GoogleMapsComponents/Maps/PolygonOptions.cs
GoogleMapsComponents/Maps/RectangleOptions.cs
GoogleMapsComponents/Maps/StrokePosition.cs
GoogleMapsComponents/Maps/SymbolPath.cs
GoogleMapsComponents/Maps/TrafficModel.cs
GoogleMapsComponents/Maps/TravelMode.cs
GoogleMapsComponents/Serialization/JsonStringEnumConverterEx.cs

This pull request addresses a critical issue in the BlazorGoogleMaps repository concerning the incorrect serialization of enums. The issue not only affected the positioning of map controls but might have also impacted other parts of the library due to improper use of the `EnumMember` attribute in JSON serialization.
- Added the `JsonConvert` attribute to all enums using the `JsonStringEnumConverterEx` converter.
- Ensured that all enums use `JsonStringEnumConverterEx` instead of `JsonStringEnumConverter`.
- Updated the `JsonStringEnumConverterEx` class to be a factory for converters, utilizing a concurrent dictionary for caching converters. This allows only one converter to be added to the `JsonSerializerOptions`, improving performance and consistency across the library.
- These changes …

Fix bug #293 Incorrect serialization of Enums

---

GoogleMapsComponents/Maps/Map.cs
GoogleMapsComponents/wwwroot/js/objectManager.js
ServerSideDemo/Pages/MapLegendPage.razor
ServerSideDemo/Pages/MapLegendPage.razor.cs
ServerSideDemo/Pages/MapsLegendPage.razor
ServerSideDemo/Shared/NavMenu.razor

This pull request fixes a bug introduced in v3.3.1, issue #298,  where OnClick events from elements in custom controls stopped working.
It also disposes used resources.
objectManager.js:
1. Removal of elem.clone() in addControls:
- Issue Addressed: Previously, elem.clone() was used, which led to problems with OnClick events in Blazor. Cloning a DOM element does not copy event listeners attached to it, causing loss of interactivity.
- Resolution: Removed the cloning process. Now, the original element (elem) is directly used, preserving its event listeners and functionality.
2. Enhanced Handling of controlParents:
- Multi-map Support: Adjusted the controlParents object to handle controls from multiple maps. 
- Proper Disposal: Ensured that controlParents is disposed of correctly when a map …

Fix bug: OnClick events from elements in custom controls not working after v3.3.1

---

GoogleMapsComponents/wwwroot/js/objectManager.js

Fixes #308 by allowing customers to exclude deprecated filed before `JSON.stringify` triggers warnings.
For example:
```Csharp
const removeDepricatedFieldsFromObject = function (obj) {
if ('place_id' in obj) {
delete obj.utc_offset
}
if ('opening_hours' in obj) {
const hours = obj.opening_hours
delete hours.open_now
}
}
const removeDepricatedFields = function (obj) {
if (Array.isArray(obj)) {
for (const element of obj) {
removeDepricatedFields(element)
}
} if (typeof obj === 'object' && obj !== null) {
removeDepricatedFieldsFromObject(obj)
}
}
window.blazorGoogleMapsBeforeStringify = function (obj) {
removeDepricatedFields(obj);
return obj;
};
```

Alow updating API response before serialization

---

GoogleMapsComponents/BlazorGoogleMapsKeyService.cs
GoogleMapsComponents/DependencyInjectionExtensions.cs
GoogleMapsComponents/GoogleMap.razor
GoogleMapsComponents/GoogleMapsComponents.csproj
GoogleMapsComponents/MapComponent.cs
GoogleMapsComponents/Maps/Map.cs
GoogleMapsComponents/Maps/MapApiLoadOptions.cs
GoogleMapsComponents/Maps/MapOptions.cs
README.md
ServerSideDemo/Pages/MapLegendPage.razor.cs
ServerSideDemo/Pages/Maps.razor
ServerSideDemo/Pages/_Host.cshtml
ServerSideDemo/Startup.cs
ServerSideDemo/wwwroot/js/serverSideScripts.js

This merge request implements the changes needed for issue https://github.com/rungwiroon/BlazorGoogleMaps/issues/326.
* Adds a new interface for a scoped service users can implement to provide API keys from async operations. 
* Adds a very basic default implementation of the service that users with single API keys can use as before.
* Updates ServerSideDemo to load serverSideScripts.js through JSInterop import command since bootstrapping loads the api after `<link>` tags are evaluated.

Implement bootstrapping via service

---

GoogleMapsComponents/GoogleMapsComponents.csproj
GoogleMapsComponents/Maps/AdvancedMarkerView.cs
GoogleMapsComponents/Maps/Extension/AdvancedMarkerList.cs
ServerSideDemo/Pages/GMap.razor.cs
ServerSideDemo/Pages/MapAdvancedMarkerListPage.razor
ServerSideDemo/Pages/MapAdvancedMarkerListPage.razor.cs
ServerSideDemo/Shared/NavMenu.razor

TODO: Rename AdvancedMarkerView class to AdvancedMarkerElement (or AdvancedMarker)

Implementing AdvancedMarkerList based on MarkerList.

---

GoogleMapsComponents/wwwroot/js/objectManager.js

I had mentioned in this comment: https://github.com/rungwiroon/BlazorGoogleMaps/issues/338#issuecomment-2267200750
I was unable to set PinElement Glyphs to HTML content properly.
After looking through the updates to objectManager.js in this commit: https://github.com/rungwiroon/BlazorGoogleMaps/commit/01fd96e93b11a56c341940f6fd95a069847e2eb5
I was able to understand that my suspicion was correct and only image URLs and text were currently supported.
I copied the above code for making an HTML element for pins to allow the same for PinElement Glyphs and it worked fine.
Before:
After:
First PR to this repo and I definitely don't understand everything going on in here, but was able to piece enough together here. I also tried to follow the codebase conventions. Feel free to make any additional …

Adding ability to make AdvancedMarkerElement Glyphs HTML content.

---

GoogleMapsComponents/Maps/CameraControlOptions.cs
GoogleMapsComponents/Maps/ColorScheme.cs
GoogleMapsComponents/Maps/MapOptions.cs
ServerSideDemo/Pages/MapAdvancedMarkerViewPage.razor

Seems that Google has added a bunch of options to the Map. This PR sync most of them. There is still `RenderingType` that requires a solution for getting the Constants. Might look into that in the future but left a TODO comment to make sure that it's atleast noticable. `RenderingType` can be controlled by the MapId (Cloud console) so it shouldn't be too bad to not be able to specify it.

Update MapOptions to support new/more options

---

GoogleMapsComponents/wwwroot/js/objectManager.js
ServerSideDemo/Pages/MapMarker.razor
ServerSideDemo/Pages/MapMarker.razor.cs

Simply make sure to always register the guidString, that we we can clean them up when disposing. Noticed that the MapData was not disposed, but it was connected to the map. This solved this issue and should solve more missing disposes (projection?) 😄

Improve disposing of mapObjects by making sure that guidString is registered for objects

---

GoogleMapsComponents/wwwroot/js/objectManager.js
ServerSideDemo/Pages/MapEvents.razor
ServerSideDemo/Pages/MapPolyline.razor
ServerSideDemo/Pages/MapServices.razor

Sorry for breaking last time, apperently my JS knowledge is limited when it comes to this stuff 😆 
Now we make sure that the item is a object (which should have support for the "in" check). Added some more disposes to server side pages to make sure that we cleanup. Also fixes some issue with the polygon "getPaths" that I noticed when testing.
Fixes #360

Fix map items dispose issue

---

GoogleMapsComponents/wwwroot/js/objectManager.js

Tiny change to allow markers to be created without a matching Map.
This is pretty important in my case since I want the advanced markers to be created (as in google taking control of the content) but I dont want them to show up on the map just yet, since they are clustered. If I add them to the map instantly all the markers blink and then are put into the cluster. 
Thanks for merging and I like the other changes you made, made it much clearer how the marker control works 🚀

Allow for creating MarkerComponent without "targeting" a map

---

README.md

Fixed small typo where s of MapS was missing in the namespace in the introduction.

Updates README.md with a small fix to a typo in the namespace

---

GoogleMapsComponents/JsObjectRefInstances.cs

Fixes thread-safety issue in JsObjectRefInstances internal dictionary

Thread-safety issue fix in JsObjectRefInstances

---

GoogleMapsComponents/Maps/Places/Autocomplete.cs

As of March 1st, 2025, google.maps.places.Autocomplete is not available to new customers. Please use google.maps.places.PlaceAutocompleteElement instead. At this time, google.maps.places.Autocomplete is not scheduled to be discontinued, but google.maps.places.PlaceAutocompleteElement is recommended over google.maps.places.Autocomplete. While google.maps.places.Autocomplete will continue to receive bug fixes for any major regressions, existing bugs in google.maps.places.Autocomplete will not be addressed. At least 12 months notice will be given before support is discontinued. Please see https://developers.google.com/maps/legacy for additional details and https://developers.google.com/maps/documentation/javascript/places-migration-overview for the migration guide.

Update Legacy places.Autocomplete -> places.PlaceAutocompleteElement

---

GoogleMapsComponents/Maps/Places/Autocomplete.cs

Reverts rungwiroon/BlazorGoogleMaps#416
@valentasm1 After testing, seems like there is compatibility issues with the past places.Autocomplete - as the new places.PlaceAutocompleteElement does not take in Input + opts and instead only takes in Opts and is it's own element.
like this for example:
<gmp-place-autocomplete
@ref="autocompleteElement"
included-region-codes="au"
@on gmp-select="OnSelected">
Since it is not compatible with previous element, I think its best to revert back to places.Autocomplete until it can be properly implemented.

Revert "Update Legacy places.Autocomplete -> places.PlaceAutocompleteElement"

---

GoogleMapsComponents/wwwroot/js/objectManager.js

Seems that I might have missed a case like this, this is a simple enough fix. The div is still referenced so not really sure that we need to handle storing it in dispose but seems that it won't hurt.

Fix issue where the pooling might race a new initialisation

---

GoogleMapsComponents/Serialization/LatLngLiteralConverter.cs

It seems that Google is rolling out the LatLngAltitudeLiteral, maybe we should switch them all to LatLngAltiude but I don't really see the point in that right now, this fixes the exceptions that occur when altitude is present.

Fix converting for LatLng throwing if altitude is present
